# Generated by Django 3.2.6 on 2021-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210903_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['date_posted']},
        ),
        migrations.AddField(
            model_name='image',
            name='photo_image',
            field=models.ImageField(default='SOME STRING', upload_to='photos/'),
        ),
    ]
